/* eslint-disable linebreak-style */
/* eslint-disable import/no-anonymous-default-export */
export default {
  COLOR_MAIN: "#4357A5",
  BACKGROUND_COLOR: "#f7f9fa",
  WHITE: "#ffffff",
  BORDER_COLOR: "#dcdfe6",
  ICON_COLOR: "#7a828b",
  TEXT_LIGHT: "#8E97A4",
  SUB_TITLE: "#A5A5A5",
  TITLE: "#6f7274",
  LIGHT_BLUE: "#00adef",
  BLUE: "#007AFF",
  RED: "#ee0a24",
  BLACK: "#000",
  LIGHT_BLACK: "#2b2b2b",
  PROCESSING_COLOR: "#ffc107",
  DARK_YELLOW: "#b4a236",
  CANCEL_COLOR: "#ff453a",
  BACKGROUND: "#F5F6F8",
  LABEL_COLOR: "#00adef",
  YELLOW: "#F6A000",
  BUTTON_BACKGROUND: "#f1f2f5",
  BACKGROUND_FORM: "#F0F1F5",
  TEXT_COLOR: "#5B6677",
  COMPLETE_COLOR: "#2ca20d",
  STAR: "#DBBA00",
};
