/* eslint-disable import/no-anonymous-default-export */
export default {
  CAN_ACTIVE: 'CAN_ACTIVE',
  CAN_ACTIVE_SUCCESS: 'CAN_ACTIVE_SUCCESS',
  CAN_ACTIVE_ERROR: 'CAN_ACTIVE_ERROR',

  LOGIN_WITH_EMAIL_PASSWORD: 'LOGIN_WITH_EMAIL_PASSWORD',
  LOGIN_WITH_EMAIL_PASSWORD_SUCCESS: 'LOGIN_WITH_EMAIL_PASSWORD_SUCCESS',
  LOGIN_WITH_EMAIL_PASSWORD_ERROR: 'LOGIN_WITH_EMAIL_PASSWORD_ERROR',

  SIGN_OUT: 'SIGN_OUT',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_ERROR: 'SIGN_OUT_ERROR'
};
