/* eslint-disable import/no-anonymous-default-export */
export default {
    CREATE_NEW_CATEGORY: 'CREATE_NEW_CATEGORY',
    CREATE_NEW_CATEGORY_SUCCESS: 'CREATE_NEW_CATEGORY_SUCCESS',
    CREATE_NEW_CATEGORY_ERROR: 'CREATE_NEW_CATEGORY_ERROR',

    FETCH_CATEGORY: "FETCH_CATEGORY",
    FETCH_CATEGORY_SUCCESS: "FETCH_CATEGORY_SUCCESS",
    FETCH_CATEGORY_ERROR: "FETCH_CATEGORY_ERROR",

    FETCH_CATEGORY_DETAIL: "FETCH_CATEGORY_DETAIL",
    FETCH_CATEGORY_DETAIL_SUCCESS: "FETCH_CATEGORY_DETAIL_SUCCESS",
    FETCH_CATEGORY_DETAIL_ERROR: "FETCH_CATEGORY_DETAIL_ERROR"

};
