/* eslint-disable import/no-anonymous-default-export */
export default {
  UPDATE_REQUEST_STATUS: "UPDATE_REQUEST_STATUS",
  UPDATE_REQUEST_STATUS_SUCCESS: "UPDATE_REQUEST_STATUS_SUCCESS",
  UPDATE_REQUEST_STATUS_ERROR: "UPDATE_REQUEST_STATUS_ERROR",
};
